### ISSUE TITLE
Unable to resolve server names

### ISSUE THREAD

**Issue by cobber** [adium/adium#12] opened 2021-02-12 14:35 UTC
I just installed Adium on Mac OS 10.14.6 (Mojave) and, even after a reboot, it doesn't seem to be able to resolve any host names. However, browsing to the hosts and e.g. `host irc.freenode.net` works just fine on the command line.

Error: Unable to connect: Error resolving irc://irc.freenode.net: nodename nor servname provided, or not known

![image](https://user-images.githubusercontent.com/31005/107780547-18233c00-6d47-11eb-8382-f877e7582572.png)

Trying to use e.g.`https://{server}` also throws the same error.

Cheers,

cobber

**Comment by ChrisForsythe** [comment] 2021-02-24 19:09
Try chat.freenode.net. Same issue?

**Comment by cobber** [comment] 2021-02-24 19:25
irc://chat.freenode.net seems to work
strange... irc.freenode.net and chat.freenode.net both have the same set of addresses according to host(1)

**Comment by ChrisForsythe** [comment] 2021-02-24 19:28
> irc://chat.freenode.net seems to work
> strange... irc.freenode.net and chat.freenode.net both have the same set of addresses according to host(1)

I'm pretty sure freenode is/was moving to chat. and cnamed irc. a while back. I think they'll eventually drop irc. entirely. Since it's working for you I'm going to close this.

If you narrow it down further and find this is the cause, feel free to open a new issue detailing the problem itself in more of a "user story" kind of way and not so much a support issue, if that makes sense.

**Closed as completed by ChrisForsythe** 2021-02-24 19:28 UTC
Labels: bug

**Comment by cobber** [comment] 2021-02-24 19:39
all good :-)

**Comment by monajalal** [comment] 2021-08-20 21:17
I am not able to connect could someone please help me?
<img width="537" alt="Screen Shot 2021-08-20 at 5 15 33 PM" src="https://user-images.githubusercontent.com/1892917/130294265-67ec5686-071c-4bd1-92af-a595c79f718c.png">
<img width="571" alt="Screen Shot 2021-08-20 at 5 17 07 PM" src="https://user-images.githubusercontent.com/1892917/130294266-05d2458f-8e8a-46a6-8579-26834e9242e9.png">
