### ISSUE TITLE
Unable to build project on macOS 11

### ISSUE THREAD

**Issue by jas8522** [adium/adium#7] opened 2020-12-05 13:50 UTC
Documenting this here so it's more clear what is going on to anyone who might be interested.

Since macOS 10.15 the biggest hurdle to any new releases of Adium has been the inability to build the project on recent releases of macOS. Notes from @RobFog on this:

> Between January and April I tested a whole bunch of builds from @Asher-. I think he managed to sort out many, many issues with building: https://github.com/adium/adium/commits/adium-1.5.11.asher But the builds he sent me were continuously misbehaving on my computer with OS X 10.11 so we were stuck there (I’m now working with Mac with 10.15).

The latest branch where work on fixing the build process is happening is here: https://github.com/adium/adium/commits/adium-1.5.11.asher.1011fix

**Comment by Asher-** [comment] 2021-03-09 16:54
This information no longer applies, plus building from current state will not result in working binary. Closing this issue as duplicate of #2.

**Closed as completed by Asher-** 2021-03-09 16:54 UTC
Labels: bug
